name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
      - name: Check
        run: ./gradlew check
